language: node_js
node_js: lts/*

install: ./run install-ci
script: ./run test-ci && ./run build-site-ci

deploy:
  provider: pages
  skip_cleanup: true
  github_token:
    secure: ObWH+5ztlsh6BV4gzDW2mP4FdN7TgaSqu1AArgA/Ongz01v7NoTh5fN3tCbVlvuxEtbt3SrA6DeULA64/J9v2wQcjwy2e+IlV24Y1WVdzv0fPPht01tZSzoke8XWMtAHJlix1TAMZanYAvlzhY8rSq5gDg2M/LgiHfIhvkzHnTgjKd+u3qn2kEVTljuAwCVP1WVVWg47knWr55Khf70t2ye4E4vfwMppYSs4XWFUloAv7UcECUPu5YMbkIgxskCkUmU+jVp8yoZZ2Stia3EoH9EIl4vmiTY2yXEetT0mBxr+X3yvXcMmAydFCjrLNFzjoFzxNVNA6E9aaIW1s4fw00793PNikf5eO1hQdCt9A4FGqm8i8ZV4iynxOHiwTjaJijp7/oahOPJcMhr7PezmxMq+kfYefXBMaeEgyDD3v974txr2EmAFEzCZHzoydk36tNGj1n7Qsg3cBvHM5sqbWv0hHwWn6eFp1CKauIQ3/jOd31b9C+zrChWoM8sDBHk0pg9N9JtEpfV9AqP26uJ7cD4YIKHxBuUtenPSvDF134+mtm73jZMPal0OPa0ml07ukUqBCi1yHn2r7RQVQf7w6RCBubaAKD0p26ZeCxl7yN21z8iPwTFRkrPqWDNt2nxM9JALz4sGcGqyIElcpoXQCe89THICEhIE8dHnqdNy9Tw=
  keep_history: true
  local_dir: project-site
  on:
    branch: master
