language: node_js
node_js: lts/*

install: ./run install-ci
script: ./run test-ci && ./run build-site-ci

deploy:
  provider: pages
  skip_cleanup: true
  github_token: ${GITHUB_TOKEN}  # See https://docs.travis-ci.com/user/deployment/pages/
  keep_history: true
  local_dir: project-site
  on:
    branch: master
