#!/bin/bash
#
# Initialize vagrant environment
# Source from ~/.bashrc

if [ "$#" != "1" ]; then
  echo "Usage: source base_env project_root_path"
else
  export PROJECT_ROOT=$1

  # Set up paths for using locally-built ffmpeg
  export LD_LIBRARY_PATH="$PROJECT_ROOT/build/ffmpeg/install/lib:$LD_LIBRARY_PATH"
  export PATH="$PROJECT_ROOT/build/ffmpeg/install/bin:$PATH"

  # Default working directory is the project
  cd $PROJECT_ROOT
fi