#!/bin/bash
#
# Script for managing an FFmpeg build environment packaged in a Docker container.
# This wraps the popular ffmpeg container: https://hub.docker.com/r/jrottenberg/ffmpeg
#
# To build and use the ffmpeg submodule within the container:
# > ./ffmpeg-container build_ffmpeg
# > ./ffmpeg-container stream_test

BASE_IMAGE_NAME=ffmpeg-build
DEV_IMAGE_NAME=ffmpeg-dev
CONTAINER_NAME=ffmpeg
DOCKERFILE_URL='https://raw.githubusercontent.com/jrottenberg/ffmpeg/master/docker-images/4.2/ubuntu/Dockerfile'
PROJECT_ROOT=$(dirname $(realpath $0))
WORKDIR=/tmp/share-space
FFMPEG_SOURCE=$WORKDIR/ffmpeg
FFMPEG_BUILD=$WORKDIR/build/ffmpeg
FFMPEG_INSTALL=$FFMPEG_BUILD/install

MEDIA_SINK_SOCKET=$WORKDIR/build/server/share-space-media-sink.sock
INFO_SINK_SOCKET=$WORKDIR/build/server/share-space-info-sink.sock

configure_ffmpeg() {
	# Run from inside container
	cd $FFMPEG_BUILD
	$FFMPEG_SOURCE/configure \
		--prefix=$FFMPEG_INSTALL \
		--enable-libvpx \
		--enable-libopus \
		--enable-libx264 \
		--enable-gpl \
		--enable-shared
}

build_ffmpeg() {
	# Run from inside container
	configure_ffmpeg && \
		make -j $(nproc) && \
		make install
}

stream_test() {
	INFO_URL=${1:-"unix://$INFO_SINK_SOCKET"}
	MEDIA_URL=${2:-"unix://$MEDIA_SINK_SOCKET"}

	# Stream an infinite video loop to the room server
	# Run from inside container
 	LD_LIBRARY_PATH="$FFMPEG_INSTALL/lib:$LD_LIBRARY_PATH" \
		$FFMPEG_INSTALL/bin/ffmpeg \
		-re \
		-i $WORKDIR/assets/earth.mp4 \
		-vf "loop=loop=-1:size=30:start=0,realtime" \
		-f webm_streaming_chunk \
		-info_url $INFO_URL \
		$MEDIA_URL
}

build_image() {
	docker build \
		--target build \
		-t $BASE_IMAGE_NAME \
		--build-arg MAKEFLAGS="-j$(($(nproc) + 1))" \
		$DOCKERFILE_URL \
		&& \
	docker build \
	  -t $DEV_IMAGE_NAME \
		-f $PROJECT_ROOT/Dockerfile-ffmpeg \
		$PROJECT_ROOT/build/container
}

start() {
	# FFmpeg is configured to install to /opt/ffmpeg. The Dockerfile then copies libs and binaries to /usr/local.
	# In order to use pkg-config to build against the libraries, we need to use the .pc files in 
	# /opt/ffmpeg/lib/pkgconfig, which point to the libraries in /opt/ffmpeg, not /usr/local. So point everything at
	# /opt/ffmpeg to make pkg-config work, even though there are ffmpeg libs and binaries in /usr/local.
	docker run \
		-itd \
		--name $CONTAINER_NAME \
		-v $PROJECT_ROOT:$WORKDIR \
		-e LD_LIBRARY_PATH=/opt/ffmpeg/lib \
		-e PKG_CONFIG_PATH=/opt/ffmpeg/lib/pkgconfig \
		$DEV_IMAGE_NAME bash
}

attach() {
	docker exec -it $CONTAINER_NAME bash
}

remove() {
	docker container stop $CONTAINER_NAME && docker container rm $CONTAINER_NAME
}

prog_name=$0
cmd=$1
shift || true

case "$cmd" in
	build_image)
		build_image $@
		;;
	start)
		start $@
		;;
	attach)
		attach $@
		;;
	remove)
		remove $@
		;;
	build_ffmpeg)
		build_ffmpeg $@
		;;
	configure_ffmpeg)
		configure_ffmpeg $@
		;;
	stream_test)
		stream_test $@
		;;
	*)
		echo "Usage: $prog_name {build_image|start|attach|remove|configure_ffmpeg|build_ffmpeg|stream_test}"
		exit 1
esac
