#!/bin/bash

quit() {
  echo $1
  exit 1
}

PROJECT_ROOT=$(dirname $(realpath $0))

cd $PROJECT_ROOT

echo "source $PROJECT_ROOT/base_env $PROJECT_ROOT" >> ~/.bashrc || \
  quit "Couldn't update bashrc"

# Install dev dependencies

echo "Installing dependencies"
(sudo apt-get -y update && \
    ./run install_node && \
    ./run install_ffmpeg_deps && \
    ./run install_gui_deps && \
    ./run start_nfs) || \
  quit "Couldn't install dependencies"

echo "Building stack"
(./run install_frontend && \
    ./run build_ffmpeg) || \
  quit "Couldn't build stack"

echo "Finished installing"