#!/bin/bash

quit() {
  echo "quitting" > quitting
  echo $1 > quitting.why
  exit 1
}

run_cmd() {
  $PROJECT_ROOT/run $1 || quit "Error running $1"
}

PROJECT_ROOT=$(dirname $(realpath $0))

echo "project root"
echo $PROJECT_ROOT
cd $PROJECT_ROOT

echo "source $PROJECT_ROOT/base_env $PROJECT_ROOT" >> ~/.bashrc || \
  quit "Couldn't update bashrc"

# Install dev dependencies

echo "Installing dependencies"
sudo apt-get -y update
    run_cmd install_node 
    run_cmd install_ffmpeg_deps
    run_cmd install_gui_deps
    run_cmd start_nfs

echo "Building stack"
# (run_cmd install_frontend && \
#     run_cmd build_ffmpeg) || \
#   quit "Couldn't build stack"

echo "Finished installing"